# Generated by Django 3.0.5 on 2020-04-17 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Область знаний')),
                ('slug', models.SlugField(default=None, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Область знания',
                'verbose_name_plural': 'Область знаний',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Группа знаний')),
                ('slug', models.SlugField(default=None, max_length=200, unique=True)),
                ('area_kn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.Area', verbose_name='Область знаний')),
            ],
            options={
                'verbose_name': 'Группа знаний',
                'verbose_name_plural': 'Группа знаний',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubGroupKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подгруппа знаний')),
                ('slug', models.SlugField(default=None, max_length=200, unique=True)),
                ('img', models.ImageField(null=True, upload_to='images', verbose_name='Изображение')),
                ('group_kn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.GroupKnowledge', verbose_name='Группа знаний')),
            ],
            options={
                'verbose_name': 'Подгруппа знаний',
                'verbose_name_plural': 'Подгруппа знаний',
                'ordering': ['name'],
            },
        ),
    ]
