# Generated by Django 3.0.5 on 2020-04-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroupknowledge',
            name='img',
        ),
    ]
