# Generated by Django 3.0.5 on 2020-04-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20200417_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupknowledge',
            options={'ordering': ['rating'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AddField(
            model_name='groupknowledge',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=500, max_digits=8, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Направление'),
        ),
    ]
